### ISSUE TITLE
Exclude completed courses from dashboard

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-ios#119]
Courses have a complete flag that is set automatically or manually. We should discuss if we want to hide completed courses from the dashboard.

**Comment by bjrne** [comment]
The API doesn't offer this attribute yet @franzliedke

**Comment by franzliedke** [comment]
Yes, it does. It's in the associated enrollment object.

**Comment by bjrne** [comment]
Fixed in 11567f8.
