### ISSUE TITLE
Improve courses date labeling

### ISSUE THREAD

**Issue by rhlff** [openHPI/xikolo-ios#124]
OpenWHO will host a lot of courses without an start or end date. Based on the `accessible` flag, these courses will be simply _available_ or _coming soon_. We have to tweak the access logic for courses a bit, as well as the UI. The displayed date will be changed to some string. We will adopt the behavior of the web platform for that, as soon as the change is released there.

**Comment by bjrne** [comment]
This doesn't need adaptions on iOS, as we currently do exactly that. We only show a date if we have one and determine accessibility by the flag. So the only change is that `active` and ? `self-paced` are the same on openWHO and should read "available?"

**Comment by rhlff** [comment]
Great, then we only have to tweak the ui for that, to show a proper state. Let's adjust that when the web client released the change, to keep the same wording.

**Comment by rhlff** [comment]
This is the new logic for the date label of courses:

### If a course has no start and end date

- _EN_: Coming soon
- _DE_: Bald verfügbar

### If a course has only a start date in past

- _EN_: Since `start_date`
- _DE_: Seit `start_date`
- WHO-only:
  - _EN_: Self-paced
  - _DE_: Selbststudium

### If a course has only a start date in future

- _EN_: Beginning `start_date`
- _DE_: Ab `start_date`

### If a course a start and end date

- `start_date` - `end_date`
