### ISSUE TITLE
Add native discussions tableview

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#136]
and show items in a web view

**Comment by bjrne** [comment]
Is the API ready for this? @franzliedke

**Comment by franzliedke** [comment]
Are we talking about the forums? If so, the JSON-API transition is half-way done in a branch somewhere on my computer. Do you want me to prioritize this in, let's say, the coming two weeks?

**Comment by bjrne** [comment]
Not necessarily. Let @jprberlin decide 🙂

**Comment by bjrne** [comment]
Close in favor of #410
