### ISSUE TITLE
Use new Enrollment API

### ISSUE THREAD

**Issue by rhlff** [openHPI/xikolo-ios#153]
Our new Enrollment API is live with all required REST methods, please refactor all deprecated API calls.

**Comment by jprberlin** [comment]
Do you want to do it yourself?

**Comment by jprberlin** [comment]
Whats the Status here?

**Comment by bjrne** [comment]
Works, but tied closely to the user model which I still have to get bug free. I was waiting for Max to finish his work to ask him for help on that.

**Comment by rhlff** [comment]
He already submitted his thesis :)

**Comment by bjrne** [comment]
Closed in #185, 50c0aeb
