### ISSUE TITLE
Add progress feedback

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#170]
We could either add a whole page dedicated to a progress overview or add an indicator to the course section titles. Depending on the level of detail we need more infos from the API.

We currently have the visited state for course items and news articles and this for a course:
```
"visits": {
    "visited": 27,
    "total": 112,
    "percentage": 24.1071428571429
},
"points": {
    "achieved": 10.6,
    "maximal": 180,
    "percentage": 5.9
},
```

**Comment by rhlff** [comment]
We will provide a dedicated progress page like in web/android. Therefore, you can use the new API endpoints for `course-progresses` and `section-progresses`. Don't use the statistics in `enrollment`, please don't even include them. Maybe we will remove them.

**Comment by bjrne** [comment]
Close in favor of #415. Duplicate of #415
