### ISSUE TITLE
Add selection for video quality

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#194]
in settings tab. use HLS options
There should be three options:
- Download Quality
- ~~Live Streaming Quality via Mobile~~ (see #108)
- ~~Live Streaming Quality via WLAN~~

All options should be textual with numbers used for techies (Bandwith and approx. MB per hour)

On the first download and the first mobile video play the user should be asked to set his defaults once.

**Comment by mathebox** [comment]
see #242

**Comment by jprberlin** [comment]
Relates to #108
