### ISSUE TITLE
Add handoff functionality

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#214]
- From iOS app to desktop safari
- From desktop safari to iOS app
- From iOS app to iOS app

requires handling of deep links in iOS app

**Comment by jprberlin** [comment]
Ok, this has a few dependencies:
1. first release app that supports deeplinks for all items
2. update the supported links file via puppet
3. now take care of writing NSUserActivities in the next release

**Comment by mathebox** [comment]
See https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html
