### ISSUE TITLE
Update travis config

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#220]
- update to xcode ~~8.3~~ 9 image
- xcpretty is shipped with the travis image [Link](https://blog.travis-ci.com/2017-03-28-xcode-83-ga-is-here)
- `pod repo update` often fails and take a while (> 7min). Is this command required? If yes, is there an alternative?

**Comment by bjrne** [comment]
`pod install` should be enough in my opinion?

**Comment by mathebox** [comment]
By only running `pod install`, travis might not be able to install the latest pod version we use locally. (This has to be validated.)

**Comment by bjrne** [comment]
But why? Aren't the versions part of the podfile travis also uses for updating pods?

**Comment by mathebox** [comment]
See https://stackoverflow.com/a/45081972/7414898

**Comment by mathebox** [comment]
travis already supports xcode 9
