### ISSUE TITLE
Use @discardableresult for sync and save methods.

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#221]
Because we don't use the return value of several method, the swift compiler creates warning. this can be resolved by using `@discardableresult`.

Method to be modified:
- `SpineHelper.save`
- `[CoreDataClass]Helper.sync...`

**Comment by bjrne** [comment]
Do you still want this?

**Comment by mathebox** [comment]
Yes. Although we have a new sync, this is still a problem. But this will be fixed with #489

**Comment by mathebox** [comment]
Oh I was wrong. Yes, we still need this, e.g. for `CourseHelper.syncCourse(...)`
