### ISSUE TITLE
Store enrollment created at in enrollment model

### ISSUE THREAD

**Issue by janrenz** [openHPI/xikolo-ios#224]

**Comment by jprberlin** [comment]
Then we could write something like enrolled since 45 days on the enrollment button

**Comment by bjrne** [comment]
This would be iOS local only first?

**Comment by jprberlin** [comment]
no, this should be the created_at from the server

**Comment by mathebox** [comment]
@janrenz Now we store the `created_at` attribute? Do you still want to show the enrolled time period in the app?
