### ISSUE TITLE
Refactor sync methods of CourseItemHelper

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#233]
`CourseItemHelper.syncRichTexts` and `CourseItemHelper.syncVideos` are pretty similar

**Comment by bjrne** [comment]
And pretty soon we will also have `CourseItemHelper.syncQuizzes` i guess

**Comment by mathebox** [comment]
Fixed in 314b2c0344157a279c68b27167a472d5683cd4e2
