### ISSUE TITLE
When the application is loaded and opens the course page first reloading this list is triggered twice

### ISSUE THREAD

**Issue by janrenz** [openHPI/xikolo-ios#247]

**Comment by jprberlin** [comment]
This will be no big issue once ETAG support is available

**Comment by bjrne** [comment]
Since this is most likely not the only part where this happens, we should definitely take a look at it. Maybe this is the anticipated point where @mathebox wants to introduce the queueing pod?

**Comment by jprberlin** [comment]
I added some (german) comments on the ETAG issue #229
