### ISSUE TITLE
Investigate missing enrollments in my courses view

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#252]

**Comment by jprberlin** [comment]
Maybe pagination? Are we sure we fetch all courses and enrolments?

**Comment by bjrne** [comment]
I suspect the NSFetchPRedicates. We don't get courses when I'm enrolled and they are neither accessible nor "preview" or "upcoming". Which should logically never happen, but it might.

And maybe there is still another error.

**Comment by jprberlin** [comment]
But do we fetch all courses and not just only the first 50?

**Comment by bjrne** [comment]
The view doesn't exist anymore
