### ISSUE TITLE
WebView Pinboard

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-ios#26]

**Comment by bjrne** [comment]
what is the api for this?

**Comment by jprberlin** [comment]
This ticket is for webview. I guess this would be simplest for a quick launch. we can then change this to native views after release.

**Comment by jprberlin** [comment]
Can you prepare this to be merged into xikolo?

**Comment by bjrne** [comment]
?

**Comment by jprberlin** [comment]
Wrong thread ...
