### ISSUE TITLE
Revise calls of UserDefault.synchronize

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#363]
**Affected Component:**
CustomUserDefaults, ...

**Expected Behavior:**
- UserDefaults.synchronize does not have to be called every time (only for time critical settings)
- see [here in discussion section](https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize)

**Comment by bjrne** [comment]
I think this is outdated since we only use it for saving video quality setting and offline setting right now. The rest is in the keychain now. Ready to close? @mathebox

**Comment by mathebox** [comment]
`de.xikolo.ios.video.playbackRate` needs still to be adapted
