### ISSUE TITLE
Remove print statements from code

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#367]
**Affected Component:**
... everything

**Expected Behavior:**
The log output should be categorized by priority levels (error, warning, info, verbose, ...).

**Additional Notes:**
Suggestion: https://github.com/SwiftyBeaver/SwiftyBeaver

**Comment by bjrne** [comment]
@mathebox What kind of installation would you propose? They say they plan to discontinue the support of cocoa pods until the end of 2018.

**Comment by mathebox** [comment]
Hm... How about combining `pod install` and the swift package manager in a single fastlan command?

**Comment by mathebox** [comment]
FYI  https://developer.apple.com/documentation/os/logging

**Comment by mathebox** [comment]
- set log levels
- optional: color coding
- include spine logging (remove env variable in scheme)

**Comment by mathebox** [comment]
We will install SwiftyBeaver via cocoapods by referring directly to the commit.
