### ISSUE TITLE
Remove developer names from source files

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#369]
**Affected Component:**
all source code files

**Expected Behavior:**
```swift
//
//  [filename].swift
//  xikolo-{common|ios|tv}
//
```

**Actual Behavior:**
```swift
//
//  [filename].swift
//  xikolo-{common|ios|tv}
//
//  Created by [developer name] on [file creation date].
//  Copyright © [year] HPI. All rights reserved.
//
```

**Additional Notes:**
There is no benefit of having the developer's name and the files creation date stored.

**Comment by bjrne** [comment]
Is there a reason for this line? 
```swift
//  xikolo-{common|ios|tv}
´´´
It's `xikolo-ios` everywhere currently since this is the projects' name.

**Comment by mathebox** [comment]
@bjrne I would also be okay if we had no file header.

PS. Have a look here. https://github.com/realm/SwiftLint/blob/master/Rules.md#file-header

**Comment by mathebox** [comment]
FYI https://useyourloaf.com/blog/changing-xcode-header-comment/
