### ISSUE TITLE
Revised allowed device orientations for each view

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#370]
**Affected Component:**
all ViewControllers

**Expected Behavior:**
Some ViewControllers do not work well in every device orientation, e.g. LoginViewController.

**Actual Behavior:**
Currently there are no restrictions.

**Additional Notes:**

**Comment by bjrne** [comment]
I think this should be thought about in the context of iPad optimization in order to not need to change things two times.
