### ISSUE TITLE
Core Data Error on Course List View after Login

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#382]
**Affected Component:**
CourseListViewController

**Expected Behavior:**
- Updates view after successful login

**Actual Behavior:**
- only show correct behavior when logging in via tap on "My Courses"
- login via settings tab or dashboard tab leads to Core Data error

**Additional Notes:**
- delegate methods of the NSFetchedResultControllers are called in the same order/way.

**Comment by jprberlin** [comment]
This affects released version 1.3

**Comment by bjrne** [comment]
Is it this error?
```
```

**Comment by bjrne** [comment]
Is it this error?
`
CoreData: error: Serious application error.  An exception was caught from the delegate of NSFetchedResultsController during a call to -controllerDidChangeContent:.  Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted). with userInfo (null)
`

**Comment by jprberlin** [comment]
Yes
