### ISSUE TITLE
Rounded corners for login button

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#386]
**Affected Component:**
Login button in LoginViewController

**Expected Behavior:**
The button should have rounded corners that match the rounded corners of the input fields.

**Comment by bjrne** [comment]
Are you sure? It's been a while since I last saw a button with rounded corners in standard iOS design. Or is it more popular with iOS 11?

**Comment by mathebox** [comment]
I can't spot any button with sharp corners in iOS 10. But there are any with round corners, e.g.:
- AppStore: download app button, "Reedem" and "send gift" buttons at the bottom of the feature tab
- "shuffle" and "repeat" buttons in music app
