### ISSUE TITLE
Don't show alert when the user enrolls in a course

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#387]
**Affected Component:**
Course Detail Page

**Expected Behavior:**
When the users taps the 'enroll' button, don't show an alert aksing if the user is sure about this.

**Actual Behavior:**
An alert asks if the users is realls sure about the enrollment.

**Additional Notes:**
To be consistent with the Android app.

**Comment by bjrne** [comment]
This was a requirement at some point. Are you sure this is sufficient? I'm happy without it, but somebody was keen on having that extra check if I remember correctly.

**Comment by mathebox** [comment]
Android and Web don't ask the user when he enrolls. We should be consistent across the platforms.
