### ISSUE TITLE
Improvements to build numbers

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#400]
## Problems
- Build number have to be increased manually
- Working only on the master branch can lead to problems
    - If a bug is found in a released version AND the development of the next minor version has already started (unfinished features, incomplete UX), the development of the required patch version has to start from an earlier commit
    - Suppose the latest minor version has a build number of n AND there was already a beta release of the next minor version. This beta version has the build number n+1 when using the approach of simply incrementing the build number. However, this means that the patch version would also have the build number n+1. If there have been multiple build for the next patch and the next minor version, we will run into merge conflicts.

## Requirements to fulfill
- Build numbers have to be numeric, but can include dots (.) as separators
- Build number have to be unique
    - To be fair there have only to be unique for a marketing version (major.minor.patch). But it can’t hurt to make them application-wide unique.
- The build number of a new build submitted to iTunes Connect has to have to higher build number compared to the latest submitted build in order to be considered the latest build (e.g. new build for beta testing)

## Suggested solution
- We use mainly two branches
    - master: the currently released version
    - (dev|develop|development): the current beta version
        - can be the next patch, minor or major version
    - when ever needed, we add some long-running feature branches
    - the dev branch is only merge with —only-fast-forward into the master branch
        - so if required, the master branch first has to be merged into the dev branch
- App release (App Store)
    - must happen on the master branch (latest commit)
    - fastlane commands
        - create screenshots (takes a while and could lead to errors)
        - upload
            - build and upload latest version
            - upload metadata (release notes, app description | all localized)
            - optional: submit to review
    - create and push git tag for this app release
- App release (Beta)
    - must happen on the dev branch (latest commit)
    - fastlane command
        - build and upload latest version
    - create and push git tag for this beta release
- Automatically calculate build numbers
    - no manual handling and no extra commit
    - done via build phase in Xcode (first build phase)
    - use git history to determine the build number
        - calculate number of commits on the branch (`git rev-list <branch-name> | wc -l | sed "s/^ *//;s/ *$//“`)
    - different calculations for app store release and beta release
        - app store: build number = <commit_count_head> (executed on master branch)
        - beta: build number = <commit_count_master>.<commit_count_head> (executed on dev branch)
            - make sure master is up-to-date and completely merge into dev branch. this can be enforce via fastlane
        - In this way the build numbers are incrementing by default but a new change/commit means a new build number
        - Furthermore, when the current dev version is release to the app store. The dev branch is merged into the master, which increments the build number and therefore create the latest build in iTunes connect.
    - to avoid merge conflicts, the build number is reseted at the end build (additional build phase)
        - In this way, the git working repository remains in a dirty state when the build fails (or is aborted). But your should not check in these changes or even better not check in after a failing build.
        - possible because the build number calculation is deterministic 
- after an App Store release the version number is incremented immediately
    - because the development for the version has now started
    - Don’t hesitate with the version increment, because it could lead to conflicts. It’s okay to skip a patch or minor version in favor of a minor / major version. In case a patch version is required but the development for the next minor version already started, see how to release an intermediate patch version in the example section.

## Examples
- regular release
    - Suppose the master branch has 10 commits (build number of app store release) and the dev branch is ahead of the master branch by 3 commits.
    - A beta release of the current dev version would have the build number 10.13
    - When the latest dev version becomes the next app store version, the dev branch is merged into the master
    - This results in a new build number for the app store release: 13
    - After the release the new app version is set on the dev branch
- intermediate patch version
    - Suppose the master branch has 10 commits (build number of app store release) and the dev branch is ahead of the master branch by 3 commits (same as for the example for a regular release).
    - A bug in the latest app store version was discovered and requires a new patch version
    - Suppose the dev branch contains commits which are not allowed to be published, we can’t use the state of the dev branch. (If this is not the case, just follow the regular release example)
    - Starting from the current master branch, the bug is fixed on a new branch. This branch contains the version increment to the next patch version, as well as the bug fix.
    - When the bug fix branch is merged into the master and the app is released (new build number 12 - if there are two commits o the bug fix branch)
    - The master branch is then merged in the dev branch. The next beta release will have the build number 12.16 (12 = commits on the master branch, 17 = 13 initial commits on dev branch + 2 commits for bugfix + 1 merge commit) (not counting additional changes on the dev branch)

## Summary
All that may sound quite complex but boils down to one or two fastlane commands on the correct branch (the commands will abort on other branches), as well as a more sophisticated yet still simple branching conventions. The rest is handled automatically.

## Tidbits
- It is possible to use the build number to determine the exact commit as long as the history of the master and dev branch are not altered (Which we should never do anyway)
- The master branch can stay completely protected.

@jprberlin @bjrne What are your thoughts on this?

**Comment by jprberlin** [comment]
I am not sure what a Beta Release is? Is it the exactly same version that will be released later as an public version? Then it should come from master? Or is it giving beta testers to Features not yet landed in master? So what do we want achieve with beta releases? Check that our releases are working fine, then this could be with apples incremental release feature.. 
maybe also we can think on how to automate fastlane based on gut tags or something in the midterm...

**Comment by mathebox** [comment]
For me, a beta release is a version of the app submitted to TestFlight, while App Store releases are submitted to Apple for review. For every App Store release there can be multiple beta releases. But those are still optional. I was thinking about beta releases for openSAP at this point.

Beta releases are made on the dev branch, while app store releases are made on the master branch. Therefore, beta releases and app store releases can have the same commits, but they will have different build numbers (but the same version number).

Phased releases via iTunes Connect are not related to beta releases.

IMHO, I don't favor releasing the applications automatically. 1 or 2 commands on the command line are not hard and we gain more flexibility.

**Comment by mathebox** [comment]
Links where I got most of the ideas from:
- http://www.ios-blog.co.uk/tutorials/quick-tips/quick-tip-how-to-automatically-update-xcode-build-numbers-from-git/
- https://blog.curtisherbert.com/automated-xcode-build-numbers-late-2016-edition/
- http://elliot.land/post/incrementing-the-xcode-build-number
