### ISSUE TITLE
Annotate PDFs

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#409]
**Affected Component:**
CourseItem: Slides (+ documents)

**Expected Behavior:**
annotate PDFs with custom notes

**Additional Notes:**
- use PDFKit? [Doc](https://developer.apple.com/documentation/pdfkit) | [WWDC 2017 Talk](https://developer.apple.com/videos/play/wwdc2017/241/) (iOS 11 only)

**Comment by mathebox** [comment]
Is this blocked by the backend inplementation?

**Comment by bjrne** [comment]
Is it?

**Comment by janrenz** [comment]
A first version could do this locally without sync
