### ISSUE TITLE
LTI exercise support

### ISSUE THREAD

**Issue by invliD** [openHPI/xikolo-ios#42]

**Comment by bjrne** [comment]
what is an LTI exercise?

**Comment by tstaubitz** [comment]
LTI = Learning Tools Interoperability. That's a standard by imsglobal to add external teaching/learning tools (tool provider) to a learning platform (tool consumer). 
For our purposes openHPI/openSAP/mooc.house/... are the tool consumers.
CodeOcean, TeamBuilder, and several other small tools are the tool providers.

LTI employs oauth for authenticating the users from tool consumer to tool provider and back.
Basic workflow:
1. User opens external exercise item in tool provider
2. User is forwarded to tool consumer - user_id, exercise_id and the users gradebook are passed to the tool provider.
3. User does whatever is necessary to earn points on tool provider
4. User submits points, earned on tool provider, to tool consumer.

**Comment by jprberlin** [comment]
From the app point of view it's an webview.

**Comment by bjrne** [comment]
Fixed in 4ba6053.
