### ISSUE TITLE
In-app language setting

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#440]
**Affected Component:**
all views

**Expected Behavior:**
The user wants to change the language of the app inside the application.
Maybe we can combine the default localization mechanism with some custom actions.

**Additional Notes:**
https://www.factorialcomplexity.com/blog/2015/01/28/how-to-change-localization-internally-in-your-ios-application.html

**Comment by bjrne** [comment]
Is this ready to try? And which version is preferred, version 1?

**Comment by mathebox** [comment]
I would prefer method 2 (no app restart). But I'm no sure if this will work.
Alternatively, we have to set every string via NSLocalizedString (so no more Storyboard localization).

**Comment by mathebox** [comment]
In iOS 13, the user can choose a preferred language for each app. Since we currently do not have the resources to implement the out own in-app language picker, we should stick to Apple's solution.

https://developer.apple.com/videos/play/wwdc2019/403/
