### ISSUE TITLE
Make video full screen automatically 

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-ios#45]
If device is held in horizontal orientation like in the YouTube app.

**Comment by jprberlin** [comment]
Like in the you tube app

**Comment by bjrne** [comment]
This will be a bigger problem than I expected: http://stackoverflow.com/questions/30817667/how-to-make-a-avplayerviewcontroller-go-to-fullscreen-programmatically/33785005

**Comment by jprberlin** [comment]
If this is a private API we should not to this till this is allowed.

**Comment by jprberlin** [comment]
Fixed by @mathebox
