### ISSUE TITLE
Refactor spotlight registration

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#459]
**Affected Component:**
CoreDataObserver

**Expected Behavior:**
When specifying the core data you have the option to select `index in spotlight` for single attributes. By using this, we can remove the `SpotlightHelper`.

**Comment by janrenz** [comment]
I am not sure if this is true. for example we still need an point where we define the URI for a model. So I kind of do like to have this explicit in the code. If this is no issue feel free to move this to the new setting.

**Comment by mathebox** [comment]
@bjrne told me that me had a look into this. I agree with him that some explicit code, which defines the URL and so on, might be a better option for us.
