### ISSUE TITLE
Hide 'open slides' button when in offline mode and slides are not downloaded

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#469]
**Affected Component:**
video vc

**Expected Behavior:**
If the app is in offline mode and the slides were not downloaded, the open slides button should be hidden. The user could tap the button and the slides wouldn't show up.

**Actual Behavior:**
The button is always shown regardless of the app state.

**Comment by bjrne** [comment]
Remove button entirely or disable it? Or show a hint and add it to a download queue?

**Comment by mathebox** [comment]
I think disabling is the best option. Please use a gray tint color in disabled state.
