### ISSUE TITLE
Fix top spacing of course detail view on iOS 10

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#474]
**Affected Component:**
CourseDetailView

**Expected Behavior:**
On iOS 10, there is an additional spacing between navigation bar and course image

**Comment by bjrne** [comment]
Also occurs in discussion web view, sso web view, but surprisingly not in quiz web view.

**Comment by mathebox** [comment]
@bjrne This might be related to this issue: https://useyourloaf.com/blog/extra-space-when-embedding-table-views/

**Comment by mathebox** [comment]
This was fixed in f04fd414414212994045e1be4b68752f33b0e3f4. Due to the new course view design, the course navigation was affected by this bug. The fix from blog post of useyourloaf resolved this issue.
