### ISSUE TITLE
Incorrect user data when using multiple accounts

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#475]
**Affected Component:**
SettingsViewController and others

**Expected Behavior:**
After the user logs out, there should be no old user data.

**Actual Behavior:**
When logging in with single sign on, then logging out, and logging in again with a different account, the first user name is displayed in the settings tab.

**Additional Notes:**
If this is due to a incorrect token, then the enrolled courses are also wrong.

**Comment by bjrne** [comment]
After extensive debugging with breakpoints I can confirm that the keychain holds the right values at any given time, but even after having the new values for the other profile, the old one still shows up again. A restart solves the problem, so it should just be an old variable somewhere. The courses still seem wrong even though the keychain holds the right values and core data seems to get cleared successfully. I will look further into it, it's just to confirm that the token is correct.

**Comment by mathebox** [comment]
Maybe we need to delete cookies as well?
