### ISSUE TITLE
Highlight hidden courses

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#480]
**Affected Component:**
CourseActivityViewController, CourseList

**Expected Behavior:**
courses that are hidden should be marked as such (e.g. with an label)

**Additional Notes:**
You have to be enrolled in a hidden course to see it in your course list

**Comment by bjrne** [comment]
Do we currently show them?That didn't use to be the case I think.

**Comment by mathebox** [comment]
Yes, a hidden course is shown if the user is enrolled in it
