### ISSUE TITLE
Add certificates view

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#509]
**Affected Component:**
CourseDecisionViewController, CourseCertificates, EnrollmentCertificates

**Expected Behavior:**
- Show certificates for each course als a separate course "area" (like learnings, discussion, ...)
- certificates will open in a webview/SFViewController (depending if the request requires our http headers)
- Make certificate view smart
  - Show only available certificates (if not achieved: disable button)
  - Show note if no certificates are available

**Comment by bjrne** [comment]
How smart should it be? Should it give hints based on progress data on how much is needed to get one of the shown certificates? Im going to start this simple, maybe open another issues with your thoughts to that if you want it.

**Comment by mathebox** [comment]
Incorporating the progress is not necessary. 

I would suggest using a table view as base for this.
- Simply hide the certificate cell completely if the given course does not offer this certificate type.
- Disable the cell if the certificate was not achieved but is available for the given course.
- Display the cell normally if the certificate was achieved.

You can use a layout two labels (similar the the course item cell) for this. The main label shown the localized certificate type. The smaller label show "Achieved"/"Not achieved" for the corresponding case.

Bonus: Add a share button to the webview.
