### ISSUE TITLE
Course Item Title is not left aligned sometimes

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#514]
**Affected Component:**
CourseItemListView

**Expected Behavior:**
Show titles left-aligned

**Actual Behavior:**
When there is no option menu in the cell, sometimes the title is stretched weirdly

**Additional Notes:**
Seen on the simulator with the biggest accessibility font, although that had no influence on the actual size of the course item title

![simulator screen shot - iphone 6 - 2018-03-19 at 21 25 17](https://user-images.githubusercontent.com/7229585/37632497-77bb1ee6-2bbc-11e8-883e-f4d990d62a79.png)

**Comment by mathebox** [comment]
Good catch! Can you investigate a bit more. Try to change the stackview's distribution option and check how this effects this bug.

![screen shot 2018-03-21 at 14 26 14](https://user-images.githubusercontent.com/1757680/37712339-e62c81c8-2d13-11e8-98f7-27e8b10533ee.png)

**Comment by bjrne** [comment]
I already did, no quick fix. I'm going to tackle this in the context of #472 (Multiple lines for course item title)

**Comment by mathebox** [comment]
This should already be fixed.
