### ISSUE TITLE
Improve design of certificates list

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#536]
**Affected Component:**
CertificatesListViewController

**Expected Behavior:**
All course content view controllers should feature a white background to present the same visual appearance. 

**Actual Behavior:**
The certificates list uses a standard table view with a light gray background.

**Additional Notes:**
Switching to collection view might be a good idea. I envision something similar to the course list. Maybe we can reuse the custom layout of the course list. The readable content guide should be respected.

**Comment by bjrne** [comment]
The grey background stems from the "grouped" table view controller style. This is necessary to have the footer texts per section I think. If you implement a custom footer with the "plain" style they should go away

**Comment by Domileo** [comment]
Hi, I can work on this if you agree ☺️

**Comment by mathebox** [comment]
Hi @Domileo. It would be great if you would tackle this task.
I just made a quick sketch how I envision the design to be.

![img_1189 copy](https://user-images.githubusercontent.com/1757680/46938048-08a26400-d063-11e8-8f43-fe09440522a6.jpg)

- certificates are displayed as cards
  - have a look at `PseudoCourseCell` and `ShadowContainerView`
  - background color of the card:
    - if achieved: brand's primary color
    - if not: light grey 
- the collection view layout should be similar to the course list
  - number of columns depend on the available width)
