### ISSUE TITLE
Make sure certificate view controller ist compatible with open who 

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#540]
**Affected Component:**
CertificateListViewController

**Expected Behavior:**
shows correct information about all certificates on all platforms

**Actual Behavior:**
currently might state wrong percentages in the footer description, like with this openWHO course where the cop needs 80% participation (https://openwho.org/courses/AMR-competency).

**Additional Notes:**

**Comment by mathebox** [comment]
@bjrne what do you mean? The requirements are displayed correctly for this course. Please double check.

**Comment by bjrne** [comment]
Correct, works as expected.
