### ISSUE TITLE
Download Videos wrongly translated

### ISSUE THREAD

**Issue by ann0see** [openHPI/xikolo-ios#561]
If I want to download all videos for a week there's a wrong translation in the German Version of the iOS App on the AppStore. It says "Alle Folien herunterladen" two times while the upper button downloads all videos of the week.
See https://imgur.com/a/HvjT6p8

**Comment by mathebox** [comment]
Thanks a lot for spotting this typo. We resolved this in 20916e6639a3fa133f1c2202e7d0e8e947c93697. 
The next app update will include this fix.
