### ISSUE TITLE
Renew layout for course activity list

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#567]
**Is your feature request related to a problem? Please describe.**
Since the course activity list can hold (too) many courses, the user can get annoyed by not finding the course he is looking for.

**Describe the solution you'd like**
~~- on iPad, we switch to a two-row layout with no scrolling. This should hold 4-6 courses depending on the width of the screen. Since this can show only a subset of the courses in the list, the last cell should open a list view controller holding all the courses of the original activity list (similar to the list holding all course, including search)~~
~~- on iPhone, we keep the current layout but limit the number of courses to a reasonable amount (5?). Similar to the iPad version, the last cell should link a complete list~~

on iPhones and iPads (better compact and regular horizontal size class), we keep the current layout but limit the number of courses to a reasonable amount (5?). Since this can show only a subset of the courses in the list, the last cell should open a list view controller holding all the courses of the original activity list (similar to the list holding all course, including search).
The course list should also open when tapping on the heading of the horizontal course list on the dashboard. Show an arrow next to the heading.

**Additional context**
~~The current version also looks kind of weird on iPads.~~
The current list layout can hold too many courses.

@janrenz Do you think we should wait for the `last_user_visit` for this to implemented?

**Comment by janrenz** [comment]
a first version with a ios only last_user_visit couild work as well

**Comment by mathebox** [comment]
Fixed in 2d44faf5fdc578ea8a7a4a5c33d5dfca1497ea33 and ad934a3e96c18a72abf067a76d6f9c76d36352f6
