### ISSUE TITLE
Check app behavior when unenrolling from a course in offline mode

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#600]
**Describe the bug**
While using the app in offline mode (e.g. Airplane mode activated), the user still can unenroll from courses. The enrollment is then only deleted locally and later deleted on the server when the device has a connection to the Internet.
In the meantime, the course should be shown as not enrolled. This includes not showing course related announcements and courses dates, as well as the course's enrollment state. At least announcements related to the course are still shown when unenrolling from a course while being offline.

**To Reproduce**
1. Activate airplane mode
1. Go to the detail view of course you are enrolled in
1. Click on `enrollment options`
1. Click on `unenroll`
1. Close course
1. Go to Announcement tab
1. See course related announcements

**Expected behavior**
Information which require an enrollment should no longer be displayed. These are currently:
- announcements
- course dates
- enrollment state

**Affected Component**
- AnnouncementListViewController
- DashboardViewController
  - CourseDateOverviewCell
  - CourseOverviewCell
- CourseCell

**Comment by caterinamandel98** [comment]
When unenrolling from a course while in offline mode not only announcements related to the course are still displayed, also course dates are still shown in the app dashboard. However, if you then click on the date overview, you will see that there are no course dates for the courses taken.
![IMG_0830](https://user-images.githubusercontent.com/38725641/90018406-2667a100-dcad-11ea-96fe-7d27ccd22f5b.PNG)
![IMG_0829](https://user-images.githubusercontent.com/38725641/90018410-28c9fb00-dcad-11ea-93de-d83978543c93.PNG)
