### ISSUE TITLE
Clear double courses after login

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#61]
After I login, the course list shows a second "version" of every course. Once i quit the app and open it again, they're gone.

**Comment by invliD** [comment]
What you did in 3a31441 is a workaround. Find the actual issue and fix it.

**Comment by bjrne** [comment]
Why? Did we find a solution? Or is this just postponed?

**Comment by jprberlin** [comment]
i thought this was fixed..

**Comment by mathebox** [comment]
Closing in favor of #345
