### ISSUE TITLE
Add scroll view to login or hide keyboard

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#63]
On small screens, you can't see the register or even login button.

**Comment by jprberlin** [comment]
We could also make the icon smaller, and the icon should be build specific

**Comment by jprberlin** [comment]
Wasn't this fixed?

**Comment by mathebox** [comment]
This should be check for small iPhones (SE, 5s, ...) and also iPads (espacially Landscape orientation)

**Comment by mathebox** [comment]
I think we won't need a scroll view for this. Just modify the autolayout constraints.

**Comment by bjrne** [comment]
The problem is when the keyboard comes up, but yeah, we can also try new constraints.

**Comment by mathebox** [comment]
Here it worked pretty well: https://github.com/schul-cloud/schulcloud-mobile-ios/commit/95376d6a5f5b7dc72607e5c783abf8305a470efe#diff-6007bd9fe1c21c13837a2dfe38f9a43aR72

We don't need to show the register and sso buttons when the keyboard is shown. But we should add a tap gesture recognizer to dismiss the keyboard when the user taps outside of the login button or the input elements.
