### ISSUE TITLE
Show images of announcements 

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#678]
**Is your feature request related to a problem? Please describe.**
An announcement can have an image. Let's display it!

**Describe the solution you'd like**
If available, show the image below the title and above the announcement text.
Make use of `SDWebImage`

**Affected Component**
AnnouncementViewController

**Additional context**
- Use rounded corners for the image view.
- The `image_url` is already getting synchronized.

**Comment by caterinamandel98** [comment]
we decided not to implement this
