### ISSUE TITLE
Support Today View

### ISSUE THREAD

**Issue by cH3n7i** [openHPI/xikolo-ios#680]
**Is your feature request related to a problem? Please describe.**
With iPadOS you are able to put widgets on your home screen. 

**Describe the solution you'd like**
While we already have a dashboard, we could re-use (parts of) it and put it into Today View.  

**Describe alternatives you've considered**
Not doing this, leaving user without a new Today View widget and sad.

**Affected Component**
Probably `DashboardViewController`

**Additional context**
https://developer.apple.com/documentation/notificationcenter/building_a_simple_widget_for_the_today_view

**Comment by mathebox** [comment]
Yeah, this was also in my mind of a while. I wasn't sure which data to display in the Today View widget but the overview of course dates seems like a good pick. Last visited courses can be opened via home screen quick action (#653).

A Today View Widget can be displayed in a collapsed and extended mode. Let's show the aggregate course dates (first card on the dashboard: due today, due in the 7 days, all course dates) in the collapsed mode. The next course date (second card on the dashboard) can be shown additionally in the extended mode.

Regarding the UI of the Today View widget, we should stick to the human interface guidelines. Luckily, we already decoupled `Common` functionality and `iOS` (main application) specific code. In this way, we can build on top of the `Common` framework.

The Today View widget isn't new in iOS 13. It was only added to the home screen on iPads in iOS 13. Previous versions of iOS, as well as iPhones, show the Today View when swiping right on the first page of the home screen. So we can remove the tag for iOS 13.
