### ISSUE TITLE
Add video description Text to video item view

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-ios#70]
There is some optional markdown available for video items

**Comment by invliD** [comment]
I've never actually seen it used. Where would you propose showing it (on tvOS)? We don't currently have any view for videos besides the video player.

**Comment by bjrne** [comment]
If you start a video or pause it on a Chromecast you have a title and a little description field as a dark overlay at the bottom of the screen, but I don't know whether this is what you want if you have text for a video that people should read.

**Comment by jprberlin** [comment]
Text should be displayed below the video in item view only. on iOS we should discuss how (and if) we do that.

**Comment by invliD** [comment]
@jprberlin: There is no item view on tvOS. When you select a video item you're immediately starting the video.
