### ISSUE TITLE
VSDG

### ISSUE THREAD

**Issue by HuuPhuocNguyen** [openHPI/xikolo-ios#740]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Type: [e.g. iPhone6, Simulator]
 - App Version: [e.g. 2.2.0]
 - Build number: [e.g. 962]

**Affected Component**
View, ViewController, ...

**Additional context**

**Comment by HuuPhuocNguyen** [comment]
Thank you

**Comment by mathebox** [comment]
Please fill out the issue template if you have feedback, request or suggestions related to this project.
