### ISSUE TITLE
Change title of helpdesk and add hint

### ISSUE THREAD

**Issue by chagedorn** [openHPI/xikolo-ios#763]
For users, it is not clearly visible that the "Hilfe" / "Help" section is the technical user support. Accordingly, please change the title and add a short hint on the bottom of the page (before the submit button), so users know that they are contacting real people rather than searching for FAQ / using a search option:

- Change title:
  - EN: Technical Support
  - DE: Technischer Support
- Show Hint on bottom of page:
  - EN: You will create a ticket that will be answered by the helpdesk team.
  - DE: Mit Absenden wird ein Ticket erstellt, das von unserem Helpdesk-Team beantwortet wird.

In addition, please add the hints from web about FAQ and ticket language/certificate, so users can more easily find the FAQ in the apps as well.

**Comment by mathebox** [comment]
Fixed in 06debba7
