### ISSUE TITLE
Add subtitles for videos

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-ios#79]
When subtitles are available for a video, the user should be able to display them. I read that the video player on iOS supports it, but please validate it. Also it would be interesting if tvOS supports it.

~~But first, the new API has to deliver links to the subtitle files. I already requested that. We use the webVTT format.~~

**Comment by rhlff** [comment]
The subtitle `vtt_url`s  are now available for the video resource in the `subtitles` hash. Thus, this feature can be implemented know.
