### ISSUE TITLE
Some PDF Slides Cannot be Opened

### ISSUE THREAD

**Issue by MrSerth** [openHPI/xikolo-ios#843]
**Describe the bug**
Some slides attached to a video in a MOOC on openHPI are not shown correctly in the mobile iOS app.

**To Reproduce**
1. Enroll in our [Python course](https://open.hpi.de/courses/pythonjunior2020) and open it on the iPad through your current courses (on the dashboard)
2. Click on *video* learning item "1.6 Turtle (1/2)".
3. Open Slides (either through clicking on the label or "See Slides" in the context menu
4. The slides are being downloaded but won't display.

**Expected behavior**
The PDFs are shown as usual.

**Screenshots**
![IMG_095F068A9AF6-1](https://user-images.githubusercontent.com/7300329/97755771-0dc39600-1afa-11eb-85f7-b5d53c067781.jpeg)

**Device (please complete the following information):**
 - Type: iPad Pro (9,7 Zoll)
 - OS: 14.1 (18A8395)
 - App Version: 2.11.0
 - Build number: 1895

**Affected Component**
View, ViewController, ...

**Additional context**
Other slides are working correctly in the app. Opening the slides through the website in Safari also works as expected. Downloading the slides first and opening these afterward doesn't change the behavior. 

[Video Item](https://open.hpi.de/courses/pythonjunior2020/items/2iKszJe4cMoAJbLgzxdX32)
[Forum Thread](https://open.hpi.de/courses/pythonjunior2020/question/0416da1a-00a1-49c5-b57b-36b7ecaa80dd)

I also attached the slides as uploaded on openHPI and the original, uncompressed file. In order to minimize the download size, all slides (incl. this one) were reduced in file size with Adobe Acrobat Pro DC. Both versions of the slide don't work. Feel free to ask for more info (e.g. the raw Keynote presentation) if needed.

[1.6 - Turtle 1.pdf](https://github.com/openHPI/xikolo-ios/files/5467621/1.6.-.Turtle.1.pdf)
[1.6 - Turtle 1.pdf](https://github.com/openHPI/xikolo-ios/files/5467622/1.6.-.Turtle.1.pdf)

**Comment by mathebox** [comment]
Already fixed with 6d8be2d91f55be1b8331137c9f0c2765b64d82f7 😉 
The update 2.11.1 will be released in the next days.
