### ISSUE TITLE
We The Peoples

### ISSUE THREAD

**Issue by ghost** [openHPI/xikolo-ios#855]
**Describe the bug**
By Phuoc Nguyen 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Type: [e.g. iPhone6, Simulator]
 - App Version: [e.g. 2.2.0]
 - Build number: [e.g. 962]

**Affected Component**
View, ViewController, ...

**Additional context**

**Comment by The-Global-Goals** [comment]
Thank you
