### ISSUE TITLE
Paging behavior for slides

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-ios#862]
**Is your feature request related to a problem? Please describe.**
Scrolling through slides should be paged instead of continuous.

**Describe the solution you'd like**
Check if there is an API for that.

**Describe alternatives you've considered**
Use QLPreviewController or PDFKit as suggested in #539

**Affected Component**
PDFWebViewController, ..

**Comment by mathebox** [comment]
With a paged scrolling behavior, the user is no longer able to quick scroll to a later part in the PDF documents. Having a continuous scrolling behavior which snaps to the single pages is unfortunately no possible with `PDFView`. 

We could consider synchronizing the video and the position in the PDF. This would be technically possible, but more slide information would be needed. Therefore, I'm closing this issue.

**Comment by tooomm** [comment]
I would prefer a page based display over continuous scrolling all day.
The possibility to always have one slide locked in, all pages always at the same location, should e.g. be more convenient when placing the video overlay for example.

>With a paged scrolling behavior, the user is no longer able to quick scroll to a later part in the PDF documents.

IMO this argument is not true. If I can flick trough pages of the slides, or even change them with a tab to the sides only (or a <br> `< 5/15 >` overlay in one edge), it can even be faster. It's also more precise.

It can always be an option of course...

**Comment by mathebox** [comment]
Thanks for your feedback @tooomm! We will look into this if possible.
