### ISSUE TITLE
Channel support 

### ISSUE THREAD

**Issue by janrenz** [openHPI/xikolo-ios#99]
Add channel support for those builds where the platform uses channels

**Comment by bjrne** [comment]
The model already exists - I'd love to have some input on how to incorporate this into our current UI.

**Comment by jprberlin** [comment]
There is a primary channel colour that we can use. We can alos think about doing like the channel landing page within the app..

**Comment by bjrne** [comment]
@janrenz Is this still relevant and do you have specific ideas?

**Comment by mathebox** [comment]
The channel will be accessible via the tab bar. Place it at second position to match the ordering of the web application (channels, courses, news | see open.sap.com). A tab bar icon already exists on my local machine.

**Model**
The Channel model was removed during the sync rewrite. So it has to added again. With API version 3.3, new attributes were introduced. API Version 3.4 will add a visual for mobile devices, so we don't have to handle `stage_logo_url`, `stage_image_url` and `stage_statement`.

**Layout**
The channel list implemented as a UICollectionView. A channel cell should include the mobile visual, title, an abbr. description (2-3 lines), and a horizontal scroll view for the first n courses (similar to the dashboard). The cell's background should be the channel color (with alpha 0.2 or similar).
Tapping anywhere on the channel cell will open the channel view featuring a complete list of courses in the given channel. Tapping on a course cell should open the course directly.
This horizontal courses scroll view should have an additional cell at the end of the row (titled " more") if the course list was truncated. The "more" course opens the channel view.

Here is a sketch for the layout:
![image 2018-03-14 14 12 53](https://user-images.githubusercontent.com/1757680/37404310-ca8fb9bc-2791-11e8-85c5-586cc485b5d1.jpg)

Here is a mockup for the Android version:
![channels_impl_1b](https://user-images.githubusercontent.com/1757680/37404325-d8811250-2791-11e8-9a57-e4b413e69c56.png)

The layout of the channel view will be similar to the courses list. Additionally it will have the mobile visual, title and description. Here is a mockup for the Android version:
![channel_detail_2](https://user-images.githubusercontent.com/1757680/37404554-7e7fb4f4-2792-11e8-9427-27837557275f.png)

fyi @bjrne

**Comment by tobiasrohloff** [comment]
Channels on openHPI are not visible to the user yet. You can use this for testing, but it needs to be disabled before releasing this brand. Besides the mobile visual, all other API changes should be rolled out already. The mobile visual will be rolled out this week, but needs to be produced and uploaded by all partners first. Again, we can upload some dummy images for testing at openHPI then.

**Comment by bjrne** [comment]
In the android mockup it seems that you used the `stage_statement` and `stage_stream` attributes. Should I also use these or just the title and the description? And should I maybe use `stage_image_url` as a fallback until the mobile visual is available on all platforms?

**Comment by mathebox** [comment]
You can use the `stage_stream` attribute and leave out the `state_statement` attribute. The later one is used in combination with `state_image_url` and `stage_logo_url` in the web version only.

Just use `mobile_image_url` (without fallback) as this is the new alternative for the apps and smaller screens.

**Comment by tobiasrohloff** [comment]
Just use `mobile_image_url` and `description`.  We will make sure that all channels have that in place before the app release.
